// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingApp.Data;

#nullable disable

namespace ParkingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ParkingApp.Models.Booking", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("CarNumber").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("CreatedDate").HasColumnType("TEXT");
                b.Property<DateTime>("EndTime").HasColumnType("TEXT");
                b.Property<int>("ParkingLotId").HasColumnType("INTEGER");
                b.Property<string>("ReceiptNumber").IsRequired().HasColumnType("TEXT");
                b.Property<int>("SpaceNumber").HasColumnType("INTEGER");
                b.Property<DateTime>("StartTime").HasColumnType("TEXT");
                b.Property<decimal>("TotalPrice").HasColumnType("decimal(10,2)");
                b.Property<int>("UserId").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("ReceiptNumber").IsUnique();
                b.HasIndex("UserId");
                b.HasIndex("ParkingLotId");
                b.ToTable("Bookings");
            });

            modelBuilder.Entity("ParkingApp.Models.ParkingLot", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedDate").HasColumnType("TEXT");
                b.Property<string>("ImagePath").IsRequired().HasMaxLength(255).HasColumnType("TEXT");
                b.Property<double>("Latitude").HasColumnType("REAL");
                b.Property<string>("Location").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<double>("Longitude").HasColumnType("REAL");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<int>("OccupiedSpaces").HasColumnType("INTEGER");
                b.Property<decimal>("PricePerHour").HasColumnType("decimal(10,2)");
                b.Property<int>("TotalSpaces").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.ToTable("ParkingLots");
            });

            modelBuilder.Entity("ParkingApp.Models.ParkingSpace", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<bool>("IsOccupied").HasColumnType("INTEGER");
                b.Property<int>("ParkingLotId").HasColumnType("INTEGER");
                b.Property<int>("SpaceNumber").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("ParkingLotId");
                b.ToTable("ParkingSpaces");
            });

            modelBuilder.Entity("ParkingApp.Models.Receipt", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<decimal>("Amount").HasColumnType("decimal(10,2)");
                b.Property<string>("CarNumber").IsRequired().HasColumnType("TEXT");
                b.Property<string>("ParkingLotName").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("PaymentDate").HasColumnType("TEXT");
                b.Property<string>("ReceiptNumber").IsRequired().HasColumnType("TEXT");
                b.Property<int>("SpaceNumber").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("ReceiptNumber").IsUnique();
                b.ToTable("Receipts");
            });

            modelBuilder.Entity("ParkingApp.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("AvatarPath").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Login").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(255).HasColumnType("TEXT");
                b.Property<int>("SuccessfulBookings").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("Login").IsUnique();
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("ParkingApp.Models.Booking", b =>
            {
                b.HasOne("ParkingApp.Models.ParkingLot", null)
                    .WithMany().HasForeignKey("ParkingLotId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("ParkingApp.Models.User", null)
                    .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("ParkingApp.Models.ParkingSpace", b =>
            {
                b.HasOne("ParkingApp.Models.ParkingLot", null)
                    .WithMany().HasForeignKey("ParkingLotId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
